# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - result/*


resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'db71b701-0133-420f-8978-94f5da8ce5d4'
  imageRepository: 'result'
  containerRegistry: 'karanazuredevops.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  name: 'azureagent'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'

- stage: Push
  displayName: Push stage
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

- stage: UpdateManifests
  displayName: Update Kubernetes Manifests

  jobs:
  - job: UpdateManifest
    displayName: Update Manifest

    steps:

    - checkout: self

    - bash: |
        chmod +x scripts/script.sh

        ./scripts/script.sh \
          result \
          karanazuredevops.azurecr.io \
          $(Build.BuildId)
      displayName: Update Kubernetes manifest
      env:
        PAT_TOKEN: $(PAT_TOKEN)
