# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - vote/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'ba47f0b2-39ca-4496-bc1d-c274d1d3b577'
  imageRepository: 'voteapp'
  containerRegistry: 'karanazuredevops.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: UpdateManifests
  displayName: Update Kubernetes Manifests

  jobs:
  - job: UpdateManifest
    displayName: Update Manifest

    steps:

    - checkout: self

    - bash: |
        chmod +x scripts/script.sh

        ./scripts/script.sh \
          voteapp \
          karanazuredevops.azurecr.io \
          $(Build.BuildId)
      displayName: Update Kubernetes manifest
      env:
        PAT_TOKEN: $(PAT_TOKEN)